// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: client.
// - Entity ID: 102019b19490f4f7441aef43d7c05389d3f.
// - Entity Version: 102019bcc5c552f7d7fa90dc0b3dacd031d.
// - Task ID: 696b9c93e6e950bb2289f8b5.
// - Task Root ID: 693c2aa501d82a4f259f4ab4.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for ClientClientSegment
 */
export enum ClientClientSegment {
  Unspecified = 0,
  Individual = 1,
  Corporate = 2,
  Government = 3,
  NonProfit = 4,
}
/**
 * Enumeration for ClientStatus
 */
export enum ClientStatus {
  Unspecified = 0,
  Active = 1,
  Inactive = 2,
  Blocked = 3,
  Pending = 4,
}


/**
 * Interface for ClientContactInfoModel
 */
export interface ClientContactInfoModel {
  email?: string | null;
  phone_primary?: string | null;
  phone_secondary?: string | null;
  preferred_channel?: string | null;
}
/**
 * Interface for ClientAddressInfoModel
 */
export interface ClientAddressInfoModel {
  street?: string | null;
  number?: string | null;
  complement?: string | null;
  neighborhood?: string | null;
  city?: string | null;
  state?: string | null;
  zip_code?: string | null;
  country?: string | null;
}

/**
 * Interface for ClientModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface ClientModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  full_name: string;
  cpf_cnpj: string;
  birth_date?: string | null;
  client_segment: ClientClientSegment;
  status: ClientStatus;
  contact_info?: ClientContactInfoModel | null;
  address_info?: ClientAddressInfoModel | null;
}

/**
 * ORM class for Client entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class ClientORM {
  private static instance: ClientORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b19490f4f7441aef43d7c05389d3f';
    this.entityName = 'client';
    this.entityVersion = '102019bcc5c552f7d7fa90dc0b3dacd031d';
    this.taskId = '696b9c93e6e950bb2289f8b5';
    this.taskRootId = '693c2aa501d82a4f259f4ab4';
  }

  /**
   * Get singleton instance of ClientORM
   */
  public static getInstance(): ClientORM {
    if (!ClientORM.instance) {
      ClientORM.instance = new ClientORM();
    }
    
    return ClientORM.instance;
  }

  /**
   * Get client by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getClientByIDs(ids: string[]): Promise<ClientModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete client by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteClientByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all Client records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllClient(): Promise<ClientModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Client record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertClient(data: ClientModel[]): Promise<ClientModel[]> {
    const structured = data.map((item) => CreateData(ClientModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Client records
   */
  async purgeAllClient(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Client records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listClient(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[ClientModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get client by Id index
   * This function gets data by index.
   */
  async getClientById(
    id: string,
  ): Promise<ClientModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) client by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setClientById(
    id: string,
    data: ClientModel
  ): Promise<ClientModel[]> {
    const index = createIndexId(
      id
    );

    const values = ClientModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete client by Id index
   */
  async deleteClientById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get client by CpfCnpj index
   * This function gets data by index.
   */
  async getClientByCpfCnpj(
    cpf_cnpj: string,
  ): Promise<ClientModel[]> {
    const index = createIndexCpfCnpj(
      cpf_cnpj
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) client by CpfCnpj index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setClientByCpfCnpj(
    cpf_cnpj: string,
    data: ClientModel
  ): Promise<ClientModel[]> {
    const index = createIndexCpfCnpj(
      cpf_cnpj
    );

    const values = ClientModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete client by CpfCnpj index
   */
  async deleteClientByCpfCnpj(
    cpf_cnpj: string
  ): Promise<void> {
    const index = createIndexCpfCnpj(
      cpf_cnpj
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get client by Status index
   * This function gets data by index.
   */
  async getClientByStatus(
    status: ClientStatus,
  ): Promise<ClientModel[]> {
    const index = createIndexStatus(
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) client by Status index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setClientByStatus(
    status: ClientStatus,
    data: ClientModel
  ): Promise<ClientModel[]> {
    const index = createIndexStatus(
      status
    );

    const values = ClientModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete client by Status index
   */
  async deleteClientByStatus(
    status: ClientStatus
  ): Promise<void> {
    const index = createIndexStatus(
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get client by ClientSegment index
   * This function gets data by index.
   */
  async getClientByClientSegment(
    client_segment: ClientClientSegment,
  ): Promise<ClientModel[]> {
    const index = createIndexClientSegment(
      client_segment
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) client by ClientSegment index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setClientByClientSegment(
    client_segment: ClientClientSegment,
    data: ClientModel
  ): Promise<ClientModel[]> {
    const index = createIndexClientSegment(
      client_segment
    );

    const values = ClientModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete client by ClientSegment index
   */
  async deleteClientByClientSegment(
    client_segment: ClientClientSegment
  ): Promise<void> {
    const index = createIndexClientSegment(
      client_segment
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get client by DataCreator index
   * This function gets data by index.
   */
  async getClientByDataCreator(
    data_creator: string,
  ): Promise<ClientModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) client by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setClientByDataCreator(
    data_creator: string,
    data: ClientModel
  ): Promise<ClientModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = ClientModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete client by DataCreator index
   */
  async deleteClientByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get client by DataUpdater index
   * This function gets data by index.
   */
  async getClientByDataUpdater(
    data_updater: string,
  ): Promise<ClientModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) client by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setClientByDataUpdater(
    data_updater: string,
    data: ClientModel
  ): Promise<ClientModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = ClientModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete client by DataUpdater index
   */
  async deleteClientByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to ClientModel data array
   */
  private resultToData(values: Data[]): ClientModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return ClientModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as ClientModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized ClientModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is ClientModel => item !== null);
  }
}

/**
 * Convert ClientModel data to Value array
 */
function ClientModelToValues(data: ClientModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'full_name', type: DataType.string, defaultValue: '' },
    { key: 'cpf_cnpj', type: DataType.string, defaultValue: '' },
    { key: 'birth_date', type: DataType.string, defaultValue: null },
    { key: 'client_segment', type: DataType.enumeration, defaultValue: 0 },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
    { key: 'contact_info', type: DataType.object, defaultValue: null },
    { key: 'address_info', type: DataType.object, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof ClientModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to ClientModel data
 */
function ClientModelFromValues(values: Value[]): ClientModel {
  const data: Partial<ClientModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'full_name':
        data.full_name = ParseValue(value, DataType.string) as string;
        break;
      case 'cpf_cnpj':
        data.cpf_cnpj = ParseValue(value, DataType.string) as string;
        break;
      case 'birth_date':
        data.birth_date = ParseValue(value, DataType.string) as string | null;
        break;
      case 'client_segment':
        data.client_segment = ParseValue(value, DataType.enumeration) as ClientClientSegment;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as ClientStatus;
        break;
      case 'contact_info':
        data.contact_info = ParseValue(value, DataType.object) as ClientContactInfoModel | null;
        break;
      case 'address_info':
        data.address_info = ParseValue(value, DataType.object) as ClientAddressInfoModel | null;
        break;
    }
  }
  
  return data as ClientModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for CpfCnpj fields
 */
function createIndexCpfCnpj(
  cpf_cnpj: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, cpf_cnpj, 'cpf_cnpj'),
  ];

  return {
    fields: ['cpf_cnpj'],
    values
  };
}
/**
 * Create index for Status fields
 */
function createIndexStatus(
  status: ClientStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['status'],
    values
  };
}
/**
 * Create index for ClientSegment fields
 */
function createIndexClientSegment(
  client_segment: ClientClientSegment
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, client_segment, 'client_segment'),
  ];

  return {
    fields: ['client_segment'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default ClientORM;