// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: notification.
// - Entity ID: 102019b1a17173b777eb1d8fa9c812877c8.
// - Entity Version: 102019bcc5c552f7d7fa90dc0b3dacd031d.
// - Task ID: 696b9c93e6e950bb2289f8b5.
// - Task Root ID: 693c2aa501d82a4f259f4ab4.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for NotificationStatus
 */
export enum NotificationStatus {
  Unspecified = 0,
  Pending = 1,
  Sent = 2,
  Failed = 3,
  Delivered = 4,
}
/**
 * Enumeration for NotificationType
 */
export enum NotificationType {
  Unspecified = 0,
  Email = 1,
  WhatsApp = 2,
}



/**
 * Interface for NotificationModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface NotificationModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  client_id: string;
  demand_id?: string | null;
  type: NotificationType;
  subject: string;
  message: string;
  status: NotificationStatus;
  sent_at?: string | null;
  delivered_at?: string | null;
  error_message?: string | null;
}

/**
 * ORM class for Notification entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class NotificationORM {
  private static instance: NotificationORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b1a17173b777eb1d8fa9c812877c8';
    this.entityName = 'notification';
    this.entityVersion = '102019bcc5c552f7d7fa90dc0b3dacd031d';
    this.taskId = '696b9c93e6e950bb2289f8b5';
    this.taskRootId = '693c2aa501d82a4f259f4ab4';
  }

  /**
   * Get singleton instance of NotificationORM
   */
  public static getInstance(): NotificationORM {
    if (!NotificationORM.instance) {
      NotificationORM.instance = new NotificationORM();
    }
    
    return NotificationORM.instance;
  }

  /**
   * Get notification by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getNotificationByIDs(ids: string[]): Promise<NotificationModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete notification by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteNotificationByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all Notification records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllNotification(): Promise<NotificationModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Notification record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertNotification(data: NotificationModel[]): Promise<NotificationModel[]> {
    const structured = data.map((item) => CreateData(NotificationModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Notification records
   */
  async purgeAllNotification(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Notification records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listNotification(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[NotificationModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get notification by Id index
   * This function gets data by index.
   */
  async getNotificationById(
    id: string,
  ): Promise<NotificationModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) notification by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNotificationById(
    id: string,
    data: NotificationModel
  ): Promise<NotificationModel[]> {
    const index = createIndexId(
      id
    );

    const values = NotificationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete notification by Id index
   */
  async deleteNotificationById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get notification by ClientId index
   * This function gets data by index.
   */
  async getNotificationByClientId(
    client_id: string,
  ): Promise<NotificationModel[]> {
    const index = createIndexClientId(
      client_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) notification by ClientId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNotificationByClientId(
    client_id: string,
    data: NotificationModel
  ): Promise<NotificationModel[]> {
    const index = createIndexClientId(
      client_id
    );

    const values = NotificationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete notification by ClientId index
   */
  async deleteNotificationByClientId(
    client_id: string
  ): Promise<void> {
    const index = createIndexClientId(
      client_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get notification by DemandId index
   * This function gets data by index.
   */
  async getNotificationByDemandId(
    demand_id: string,
  ): Promise<NotificationModel[]> {
    const index = createIndexDemandId(
      demand_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) notification by DemandId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNotificationByDemandId(
    demand_id: string,
    data: NotificationModel
  ): Promise<NotificationModel[]> {
    const index = createIndexDemandId(
      demand_id
    );

    const values = NotificationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete notification by DemandId index
   */
  async deleteNotificationByDemandId(
    demand_id: string
  ): Promise<void> {
    const index = createIndexDemandId(
      demand_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get notification by Status index
   * This function gets data by index.
   */
  async getNotificationByStatus(
    status: NotificationStatus,
  ): Promise<NotificationModel[]> {
    const index = createIndexStatus(
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) notification by Status index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNotificationByStatus(
    status: NotificationStatus,
    data: NotificationModel
  ): Promise<NotificationModel[]> {
    const index = createIndexStatus(
      status
    );

    const values = NotificationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete notification by Status index
   */
  async deleteNotificationByStatus(
    status: NotificationStatus
  ): Promise<void> {
    const index = createIndexStatus(
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get notification by Type index
   * This function gets data by index.
   */
  async getNotificationByType(
    type: NotificationType,
  ): Promise<NotificationModel[]> {
    const index = createIndexType(
      type
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) notification by Type index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNotificationByType(
    type: NotificationType,
    data: NotificationModel
  ): Promise<NotificationModel[]> {
    const index = createIndexType(
      type
    );

    const values = NotificationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete notification by Type index
   */
  async deleteNotificationByType(
    type: NotificationType
  ): Promise<void> {
    const index = createIndexType(
      type
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get notification by DataCreator index
   * This function gets data by index.
   */
  async getNotificationByDataCreator(
    data_creator: string,
  ): Promise<NotificationModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) notification by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNotificationByDataCreator(
    data_creator: string,
    data: NotificationModel
  ): Promise<NotificationModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = NotificationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete notification by DataCreator index
   */
  async deleteNotificationByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get notification by DataUpdater index
   * This function gets data by index.
   */
  async getNotificationByDataUpdater(
    data_updater: string,
  ): Promise<NotificationModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) notification by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNotificationByDataUpdater(
    data_updater: string,
    data: NotificationModel
  ): Promise<NotificationModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = NotificationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete notification by DataUpdater index
   */
  async deleteNotificationByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to NotificationModel data array
   */
  private resultToData(values: Data[]): NotificationModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return NotificationModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as NotificationModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized NotificationModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is NotificationModel => item !== null);
  }
}

/**
 * Convert NotificationModel data to Value array
 */
function NotificationModelToValues(data: NotificationModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'client_id', type: DataType.string, defaultValue: '' },
    { key: 'demand_id', type: DataType.string, defaultValue: null },
    { key: 'type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'subject', type: DataType.string, defaultValue: '' },
    { key: 'message', type: DataType.string, defaultValue: '' },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
    { key: 'sent_at', type: DataType.string, defaultValue: null },
    { key: 'delivered_at', type: DataType.string, defaultValue: null },
    { key: 'error_message', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof NotificationModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to NotificationModel data
 */
function NotificationModelFromValues(values: Value[]): NotificationModel {
  const data: Partial<NotificationModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'client_id':
        data.client_id = ParseValue(value, DataType.string) as string;
        break;
      case 'demand_id':
        data.demand_id = ParseValue(value, DataType.string) as string | null;
        break;
      case 'type':
        data.type = ParseValue(value, DataType.enumeration) as NotificationType;
        break;
      case 'subject':
        data.subject = ParseValue(value, DataType.string) as string;
        break;
      case 'message':
        data.message = ParseValue(value, DataType.string) as string;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as NotificationStatus;
        break;
      case 'sent_at':
        data.sent_at = ParseValue(value, DataType.string) as string | null;
        break;
      case 'delivered_at':
        data.delivered_at = ParseValue(value, DataType.string) as string | null;
        break;
      case 'error_message':
        data.error_message = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as NotificationModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for ClientId fields
 */
function createIndexClientId(
  client_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, client_id, 'client_id'),
  ];

  return {
    fields: ['client_id'],
    values
  };
}
/**
 * Create index for DemandId fields
 */
function createIndexDemandId(
  demand_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, demand_id, 'demand_id'),
  ];

  return {
    fields: ['demand_id'],
    values
  };
}
/**
 * Create index for Status fields
 */
function createIndexStatus(
  status: NotificationStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['status'],
    values
  };
}
/**
 * Create index for Type fields
 */
function createIndexType(
  type: NotificationType
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, type, 'type'),
  ];

  return {
    fields: ['type'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default NotificationORM;