// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: vehicle.
// - Entity ID: 102019b19490f4e7dad915975c4295fd878.
// - Entity Version: 102019bcc5c552f7d7fa90dc0b3dacd031d.
// - Task ID: 696b9c93e6e950bb2289f8b5.
// - Task Root ID: 693c2aa501d82a4f259f4ab4.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for VehicleVehicleType
 */
export enum VehicleVehicleType {
  Unspecified = 0,
  Car = 1,
  Motorcycle = 2,
  Truck = 3,
  Bus = 4,
  Van = 5,
  Other = 6,
}


/**
 * Interface for VehicleVehicleInfoModel
 */
export interface VehicleVehicleInfoModel {
  brand: string;
  model: string;
  year: number;
  plate: string;
  chassis?: string | null;
  renavam?: string | null;
}
/**
 * Interface for VehicleTaxExemptionModel
 */
export interface VehicleTaxExemptionModel {
  ipi_exempt: boolean;
  icms_exempt: boolean;
  ipva_exempt: boolean;
  exemption_date?: string | null;
  notes?: string | null;
}

/**
 * Interface for VehicleModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface VehicleModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  client_id: string;
  vehicle_type: VehicleVehicleType;
  vehicle_info: VehicleVehicleInfoModel;
  tax_exemption?: VehicleTaxExemptionModel | null;
}

/**
 * ORM class for Vehicle entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class VehicleORM {
  private static instance: VehicleORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b19490f4e7dad915975c4295fd878';
    this.entityName = 'vehicle';
    this.entityVersion = '102019bcc5c552f7d7fa90dc0b3dacd031d';
    this.taskId = '696b9c93e6e950bb2289f8b5';
    this.taskRootId = '693c2aa501d82a4f259f4ab4';
  }

  /**
   * Get singleton instance of VehicleORM
   */
  public static getInstance(): VehicleORM {
    if (!VehicleORM.instance) {
      VehicleORM.instance = new VehicleORM();
    }
    
    return VehicleORM.instance;
  }

  /**
   * Get vehicle by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getVehicleByIDs(ids: string[]): Promise<VehicleModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete vehicle by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteVehicleByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all Vehicle records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllVehicle(): Promise<VehicleModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Vehicle record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertVehicle(data: VehicleModel[]): Promise<VehicleModel[]> {
    const structured = data.map((item) => CreateData(VehicleModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Vehicle records
   */
  async purgeAllVehicle(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Vehicle records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listVehicle(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[VehicleModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get vehicle by Id index
   * This function gets data by index.
   */
  async getVehicleById(
    id: string,
  ): Promise<VehicleModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) vehicle by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVehicleById(
    id: string,
    data: VehicleModel
  ): Promise<VehicleModel[]> {
    const index = createIndexId(
      id
    );

    const values = VehicleModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete vehicle by Id index
   */
  async deleteVehicleById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get vehicle by ClientId index
   * This function gets data by index.
   */
  async getVehicleByClientId(
    client_id: string,
  ): Promise<VehicleModel[]> {
    const index = createIndexClientId(
      client_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) vehicle by ClientId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVehicleByClientId(
    client_id: string,
    data: VehicleModel
  ): Promise<VehicleModel[]> {
    const index = createIndexClientId(
      client_id
    );

    const values = VehicleModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete vehicle by ClientId index
   */
  async deleteVehicleByClientId(
    client_id: string
  ): Promise<void> {
    const index = createIndexClientId(
      client_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get vehicle by VehicleType index
   * This function gets data by index.
   */
  async getVehicleByVehicleType(
    vehicle_type: VehicleVehicleType,
  ): Promise<VehicleModel[]> {
    const index = createIndexVehicleType(
      vehicle_type
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) vehicle by VehicleType index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVehicleByVehicleType(
    vehicle_type: VehicleVehicleType,
    data: VehicleModel
  ): Promise<VehicleModel[]> {
    const index = createIndexVehicleType(
      vehicle_type
    );

    const values = VehicleModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete vehicle by VehicleType index
   */
  async deleteVehicleByVehicleType(
    vehicle_type: VehicleVehicleType
  ): Promise<void> {
    const index = createIndexVehicleType(
      vehicle_type
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get vehicle by DataCreator index
   * This function gets data by index.
   */
  async getVehicleByDataCreator(
    data_creator: string,
  ): Promise<VehicleModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) vehicle by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVehicleByDataCreator(
    data_creator: string,
    data: VehicleModel
  ): Promise<VehicleModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = VehicleModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete vehicle by DataCreator index
   */
  async deleteVehicleByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get vehicle by DataUpdater index
   * This function gets data by index.
   */
  async getVehicleByDataUpdater(
    data_updater: string,
  ): Promise<VehicleModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) vehicle by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVehicleByDataUpdater(
    data_updater: string,
    data: VehicleModel
  ): Promise<VehicleModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = VehicleModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete vehicle by DataUpdater index
   */
  async deleteVehicleByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to VehicleModel data array
   */
  private resultToData(values: Data[]): VehicleModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return VehicleModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as VehicleModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized VehicleModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is VehicleModel => item !== null);
  }
}

/**
 * Convert VehicleModel data to Value array
 */
function VehicleModelToValues(data: VehicleModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'client_id', type: DataType.string, defaultValue: '' },
    { key: 'vehicle_type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'vehicle_info', type: DataType.object, defaultValue: {} },
    { key: 'tax_exemption', type: DataType.object, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof VehicleModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to VehicleModel data
 */
function VehicleModelFromValues(values: Value[]): VehicleModel {
  const data: Partial<VehicleModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'client_id':
        data.client_id = ParseValue(value, DataType.string) as string;
        break;
      case 'vehicle_type':
        data.vehicle_type = ParseValue(value, DataType.enumeration) as VehicleVehicleType;
        break;
      case 'vehicle_info':
        data.vehicle_info = ParseValue(value, DataType.object) as VehicleVehicleInfoModel;
        break;
      case 'tax_exemption':
        data.tax_exemption = ParseValue(value, DataType.object) as VehicleTaxExemptionModel | null;
        break;
    }
  }
  
  return data as VehicleModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for ClientId fields
 */
function createIndexClientId(
  client_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, client_id, 'client_id'),
  ];

  return {
    fields: ['client_id'],
    values
  };
}
/**
 * Create index for VehicleType fields
 */
function createIndexVehicleType(
  vehicle_type: VehicleVehicleType
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, vehicle_type, 'vehicle_type'),
  ];

  return {
    fields: ['vehicle_type'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default VehicleORM;