// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: interaction.
// - Entity ID: 102019b1a17173b71c79962c5a6459d5955.
// - Entity Version: 102019bcc5c552f7d7fa90dc0b3dacd031d.
// - Task ID: 696b9c93e6e950bb2289f8b5.
// - Task Root ID: 693c2aa501d82a4f259f4ab4.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for InteractionInteractionType
 */
export enum InteractionInteractionType {
  Unspecified = 0,
  WhatsApp = 1,
  Email = 2,
  InPerson = 3,
  Phone = 4,
  System = 5,
}
/**
 * Enumeration for InteractionPriority
 */
export enum InteractionPriority {
  Unspecified = 0,
  Low = 1,
  Normal = 2,
  High = 3,
  Urgent = 4,
}
/**
 * Enumeration for InteractionStatus
 */
export enum InteractionStatus {
  Unspecified = 0,
  Pending = 1,
  InProgress = 2,
  Resolved = 3,
  Archived = 4,
}



/**
 * Interface for InteractionModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface InteractionModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  client_id: string;
  demand_id?: string | null;
  interaction_type: InteractionInteractionType;
  subject: string;
  description: string;
  priority: InteractionPriority;
  status: InteractionStatus;
  resolved_at?: string | null;
  suggested_action?: string | null;
}

/**
 * ORM class for Interaction entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class InteractionORM {
  private static instance: InteractionORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b1a17173b71c79962c5a6459d5955';
    this.entityName = 'interaction';
    this.entityVersion = '102019bcc5c552f7d7fa90dc0b3dacd031d';
    this.taskId = '696b9c93e6e950bb2289f8b5';
    this.taskRootId = '693c2aa501d82a4f259f4ab4';
  }

  /**
   * Get singleton instance of InteractionORM
   */
  public static getInstance(): InteractionORM {
    if (!InteractionORM.instance) {
      InteractionORM.instance = new InteractionORM();
    }
    
    return InteractionORM.instance;
  }

  /**
   * Get interaction by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getInteractionByIDs(ids: string[]): Promise<InteractionModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete interaction by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteInteractionByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all Interaction records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllInteraction(): Promise<InteractionModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Interaction record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertInteraction(data: InteractionModel[]): Promise<InteractionModel[]> {
    const structured = data.map((item) => CreateData(InteractionModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Interaction records
   */
  async purgeAllInteraction(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Interaction records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listInteraction(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[InteractionModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get interaction by Id index
   * This function gets data by index.
   */
  async getInteractionById(
    id: string,
  ): Promise<InteractionModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) interaction by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setInteractionById(
    id: string,
    data: InteractionModel
  ): Promise<InteractionModel[]> {
    const index = createIndexId(
      id
    );

    const values = InteractionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete interaction by Id index
   */
  async deleteInteractionById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get interaction by ClientId index
   * This function gets data by index.
   */
  async getInteractionByClientId(
    client_id: string,
  ): Promise<InteractionModel[]> {
    const index = createIndexClientId(
      client_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) interaction by ClientId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setInteractionByClientId(
    client_id: string,
    data: InteractionModel
  ): Promise<InteractionModel[]> {
    const index = createIndexClientId(
      client_id
    );

    const values = InteractionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete interaction by ClientId index
   */
  async deleteInteractionByClientId(
    client_id: string
  ): Promise<void> {
    const index = createIndexClientId(
      client_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get interaction by DemandId index
   * This function gets data by index.
   */
  async getInteractionByDemandId(
    demand_id: string,
  ): Promise<InteractionModel[]> {
    const index = createIndexDemandId(
      demand_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) interaction by DemandId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setInteractionByDemandId(
    demand_id: string,
    data: InteractionModel
  ): Promise<InteractionModel[]> {
    const index = createIndexDemandId(
      demand_id
    );

    const values = InteractionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete interaction by DemandId index
   */
  async deleteInteractionByDemandId(
    demand_id: string
  ): Promise<void> {
    const index = createIndexDemandId(
      demand_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get interaction by Status index
   * This function gets data by index.
   */
  async getInteractionByStatus(
    status: InteractionStatus,
  ): Promise<InteractionModel[]> {
    const index = createIndexStatus(
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) interaction by Status index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setInteractionByStatus(
    status: InteractionStatus,
    data: InteractionModel
  ): Promise<InteractionModel[]> {
    const index = createIndexStatus(
      status
    );

    const values = InteractionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete interaction by Status index
   */
  async deleteInteractionByStatus(
    status: InteractionStatus
  ): Promise<void> {
    const index = createIndexStatus(
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get interaction by InteractionType index
   * This function gets data by index.
   */
  async getInteractionByInteractionType(
    interaction_type: InteractionInteractionType,
  ): Promise<InteractionModel[]> {
    const index = createIndexInteractionType(
      interaction_type
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) interaction by InteractionType index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setInteractionByInteractionType(
    interaction_type: InteractionInteractionType,
    data: InteractionModel
  ): Promise<InteractionModel[]> {
    const index = createIndexInteractionType(
      interaction_type
    );

    const values = InteractionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete interaction by InteractionType index
   */
  async deleteInteractionByInteractionType(
    interaction_type: InteractionInteractionType
  ): Promise<void> {
    const index = createIndexInteractionType(
      interaction_type
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get interaction by Priority index
   * This function gets data by index.
   */
  async getInteractionByPriority(
    priority: InteractionPriority,
  ): Promise<InteractionModel[]> {
    const index = createIndexPriority(
      priority
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) interaction by Priority index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setInteractionByPriority(
    priority: InteractionPriority,
    data: InteractionModel
  ): Promise<InteractionModel[]> {
    const index = createIndexPriority(
      priority
    );

    const values = InteractionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete interaction by Priority index
   */
  async deleteInteractionByPriority(
    priority: InteractionPriority
  ): Promise<void> {
    const index = createIndexPriority(
      priority
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get interaction by DataCreator index
   * This function gets data by index.
   */
  async getInteractionByDataCreator(
    data_creator: string,
  ): Promise<InteractionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) interaction by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setInteractionByDataCreator(
    data_creator: string,
    data: InteractionModel
  ): Promise<InteractionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = InteractionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete interaction by DataCreator index
   */
  async deleteInteractionByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get interaction by DataUpdater index
   * This function gets data by index.
   */
  async getInteractionByDataUpdater(
    data_updater: string,
  ): Promise<InteractionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) interaction by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setInteractionByDataUpdater(
    data_updater: string,
    data: InteractionModel
  ): Promise<InteractionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = InteractionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete interaction by DataUpdater index
   */
  async deleteInteractionByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to InteractionModel data array
   */
  private resultToData(values: Data[]): InteractionModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return InteractionModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as InteractionModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized InteractionModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is InteractionModel => item !== null);
  }
}

/**
 * Convert InteractionModel data to Value array
 */
function InteractionModelToValues(data: InteractionModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'client_id', type: DataType.string, defaultValue: '' },
    { key: 'demand_id', type: DataType.string, defaultValue: null },
    { key: 'interaction_type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'subject', type: DataType.string, defaultValue: '' },
    { key: 'description', type: DataType.string, defaultValue: '' },
    { key: 'priority', type: DataType.enumeration, defaultValue: 0 },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
    { key: 'resolved_at', type: DataType.string, defaultValue: null },
    { key: 'suggested_action', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof InteractionModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to InteractionModel data
 */
function InteractionModelFromValues(values: Value[]): InteractionModel {
  const data: Partial<InteractionModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'client_id':
        data.client_id = ParseValue(value, DataType.string) as string;
        break;
      case 'demand_id':
        data.demand_id = ParseValue(value, DataType.string) as string | null;
        break;
      case 'interaction_type':
        data.interaction_type = ParseValue(value, DataType.enumeration) as InteractionInteractionType;
        break;
      case 'subject':
        data.subject = ParseValue(value, DataType.string) as string;
        break;
      case 'description':
        data.description = ParseValue(value, DataType.string) as string;
        break;
      case 'priority':
        data.priority = ParseValue(value, DataType.enumeration) as InteractionPriority;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as InteractionStatus;
        break;
      case 'resolved_at':
        data.resolved_at = ParseValue(value, DataType.string) as string | null;
        break;
      case 'suggested_action':
        data.suggested_action = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as InteractionModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for ClientId fields
 */
function createIndexClientId(
  client_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, client_id, 'client_id'),
  ];

  return {
    fields: ['client_id'],
    values
  };
}
/**
 * Create index for DemandId fields
 */
function createIndexDemandId(
  demand_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, demand_id, 'demand_id'),
  ];

  return {
    fields: ['demand_id'],
    values
  };
}
/**
 * Create index for Status fields
 */
function createIndexStatus(
  status: InteractionStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['status'],
    values
  };
}
/**
 * Create index for InteractionType fields
 */
function createIndexInteractionType(
  interaction_type: InteractionInteractionType
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, interaction_type, 'interaction_type'),
  ];

  return {
    fields: ['interaction_type'],
    values
  };
}
/**
 * Create index for Priority fields
 */
function createIndexPriority(
  priority: InteractionPriority
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, priority, 'priority'),
  ];

  return {
    fields: ['priority'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default InteractionORM;