// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: demand.
// - Entity ID: 102019b19490f4f7a72803514422f3a6c34.
// - Entity Version: 102019bcc5c552f7d7fa90dc0b3dacd031d.
// - Task ID: 696b9c93e6e950bb2289f8b5.
// - Task Root ID: 693c2aa501d82a4f259f4ab4.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for DemandDemandType
 */
export enum DemandDemandType {
  Unspecified = 0,
  Civil = 1,
  Criminal = 2,
  Labor = 3,
  Tax = 4,
  Administrative = 5,
  SocialSecurity = 6,
  Other = 7,
}
/**
 * Enumeration for DemandPriority
 */
export enum DemandPriority {
  Unspecified = 0,
  Low = 1,
  Medium = 2,
  High = 3,
  Critical = 4,
}
/**
 * Enumeration for DemandStatus
 */
export enum DemandStatus {
  Unspecified = 0,
  New = 1,
  InProgress = 2,
  Waiting = 3,
  Suspended = 4,
  Concluded = 5,
  Archived = 6,
}


/**
 * Interface for DemandDatesModel
 */
export interface DemandDatesModel {
  registration_date?: string | null;
  start_date?: string | null;
  deadline?: string | null;
  conclusion_date?: string | null;
}
/**
 * Interface for DemandProtocolInfoModel
 */
export interface DemandProtocolInfoModel {
  protocol_number?: string | null;
  protocol_date?: string | null;
  protocol_organ?: string | null;
}
/**
 * Interface for DemandValuesModel
 */
export interface DemandValuesModel {
  contract_value?: number | null;
  paid_value?: number | null;
  balance_value?: number | null;
}

/**
 * Interface for DemandModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface DemandModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  client_id: string;
  demand_number?: string | null;
  demand_type: DemandDemandType;
  status: DemandStatus;
  priority: DemandPriority;
  description?: string | null;
  dates?: DemandDatesModel | null;
  protocol_info?: DemandProtocolInfoModel | null;
  values?: DemandValuesModel | null;
}

/**
 * ORM class for Demand entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class DemandORM {
  private static instance: DemandORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b19490f4f7a72803514422f3a6c34';
    this.entityName = 'demand';
    this.entityVersion = '102019bcc5c552f7d7fa90dc0b3dacd031d';
    this.taskId = '696b9c93e6e950bb2289f8b5';
    this.taskRootId = '693c2aa501d82a4f259f4ab4';
  }

  /**
   * Get singleton instance of DemandORM
   */
  public static getInstance(): DemandORM {
    if (!DemandORM.instance) {
      DemandORM.instance = new DemandORM();
    }
    
    return DemandORM.instance;
  }

  /**
   * Get demand by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getDemandByIDs(ids: string[]): Promise<DemandModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete demand by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteDemandByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all Demand records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllDemand(): Promise<DemandModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Demand record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertDemand(data: DemandModel[]): Promise<DemandModel[]> {
    const structured = data.map((item) => CreateData(DemandModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Demand records
   */
  async purgeAllDemand(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Demand records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listDemand(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[DemandModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get demand by Id index
   * This function gets data by index.
   */
  async getDemandById(
    id: string,
  ): Promise<DemandModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) demand by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDemandById(
    id: string,
    data: DemandModel
  ): Promise<DemandModel[]> {
    const index = createIndexId(
      id
    );

    const values = DemandModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete demand by Id index
   */
  async deleteDemandById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get demand by ClientId index
   * This function gets data by index.
   */
  async getDemandByClientId(
    client_id: string,
  ): Promise<DemandModel[]> {
    const index = createIndexClientId(
      client_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) demand by ClientId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDemandByClientId(
    client_id: string,
    data: DemandModel
  ): Promise<DemandModel[]> {
    const index = createIndexClientId(
      client_id
    );

    const values = DemandModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete demand by ClientId index
   */
  async deleteDemandByClientId(
    client_id: string
  ): Promise<void> {
    const index = createIndexClientId(
      client_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get demand by DemandNumber index
   * This function gets data by index.
   */
  async getDemandByDemandNumber(
    demand_number: string,
  ): Promise<DemandModel[]> {
    const index = createIndexDemandNumber(
      demand_number
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) demand by DemandNumber index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDemandByDemandNumber(
    demand_number: string,
    data: DemandModel
  ): Promise<DemandModel[]> {
    const index = createIndexDemandNumber(
      demand_number
    );

    const values = DemandModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete demand by DemandNumber index
   */
  async deleteDemandByDemandNumber(
    demand_number: string
  ): Promise<void> {
    const index = createIndexDemandNumber(
      demand_number
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get demand by Status index
   * This function gets data by index.
   */
  async getDemandByStatus(
    status: DemandStatus,
  ): Promise<DemandModel[]> {
    const index = createIndexStatus(
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) demand by Status index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDemandByStatus(
    status: DemandStatus,
    data: DemandModel
  ): Promise<DemandModel[]> {
    const index = createIndexStatus(
      status
    );

    const values = DemandModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete demand by Status index
   */
  async deleteDemandByStatus(
    status: DemandStatus
  ): Promise<void> {
    const index = createIndexStatus(
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get demand by DemandType index
   * This function gets data by index.
   */
  async getDemandByDemandType(
    demand_type: DemandDemandType,
  ): Promise<DemandModel[]> {
    const index = createIndexDemandType(
      demand_type
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) demand by DemandType index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDemandByDemandType(
    demand_type: DemandDemandType,
    data: DemandModel
  ): Promise<DemandModel[]> {
    const index = createIndexDemandType(
      demand_type
    );

    const values = DemandModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete demand by DemandType index
   */
  async deleteDemandByDemandType(
    demand_type: DemandDemandType
  ): Promise<void> {
    const index = createIndexDemandType(
      demand_type
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get demand by DataCreator index
   * This function gets data by index.
   */
  async getDemandByDataCreator(
    data_creator: string,
  ): Promise<DemandModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) demand by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDemandByDataCreator(
    data_creator: string,
    data: DemandModel
  ): Promise<DemandModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = DemandModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete demand by DataCreator index
   */
  async deleteDemandByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get demand by DataUpdater index
   * This function gets data by index.
   */
  async getDemandByDataUpdater(
    data_updater: string,
  ): Promise<DemandModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) demand by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDemandByDataUpdater(
    data_updater: string,
    data: DemandModel
  ): Promise<DemandModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = DemandModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete demand by DataUpdater index
   */
  async deleteDemandByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to DemandModel data array
   */
  private resultToData(values: Data[]): DemandModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return DemandModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as DemandModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized DemandModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is DemandModel => item !== null);
  }
}

/**
 * Convert DemandModel data to Value array
 */
function DemandModelToValues(data: DemandModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'client_id', type: DataType.string, defaultValue: '' },
    { key: 'demand_number', type: DataType.string, defaultValue: null },
    { key: 'demand_type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
    { key: 'priority', type: DataType.enumeration, defaultValue: 0 },
    { key: 'description', type: DataType.string, defaultValue: null },
    { key: 'dates', type: DataType.object, defaultValue: null },
    { key: 'protocol_info', type: DataType.object, defaultValue: null },
    { key: 'values', type: DataType.object, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof DemandModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to DemandModel data
 */
function DemandModelFromValues(values: Value[]): DemandModel {
  const data: Partial<DemandModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'client_id':
        data.client_id = ParseValue(value, DataType.string) as string;
        break;
      case 'demand_number':
        data.demand_number = ParseValue(value, DataType.string) as string | null;
        break;
      case 'demand_type':
        data.demand_type = ParseValue(value, DataType.enumeration) as DemandDemandType;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as DemandStatus;
        break;
      case 'priority':
        data.priority = ParseValue(value, DataType.enumeration) as DemandPriority;
        break;
      case 'description':
        data.description = ParseValue(value, DataType.string) as string | null;
        break;
      case 'dates':
        data.dates = ParseValue(value, DataType.object) as DemandDatesModel | null;
        break;
      case 'protocol_info':
        data.protocol_info = ParseValue(value, DataType.object) as DemandProtocolInfoModel | null;
        break;
      case 'values':
        data.values = ParseValue(value, DataType.object) as DemandValuesModel | null;
        break;
    }
  }
  
  return data as DemandModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for ClientId fields
 */
function createIndexClientId(
  client_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, client_id, 'client_id'),
  ];

  return {
    fields: ['client_id'],
    values
  };
}
/**
 * Create index for DemandNumber fields
 */
function createIndexDemandNumber(
  demand_number: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, demand_number, 'demand_number'),
  ];

  return {
    fields: ['demand_number'],
    values
  };
}
/**
 * Create index for Status fields
 */
function createIndexStatus(
  status: DemandStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['status'],
    values
  };
}
/**
 * Create index for DemandType fields
 */
function createIndexDemandType(
  demand_type: DemandDemandType
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, demand_type, 'demand_type'),
  ];

  return {
    fields: ['demand_type'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default DemandORM;