// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: document.
// - Entity ID: 102019b19490f507193aa7678742cfd6655.
// - Entity Version: 102019bcc5c552f7d7fa90dc0b3dacd031d.
// - Task ID: 696b9c93e6e950bb2289f8b5.
// - Task Root ID: 693c2aa501d82a4f259f4ab4.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for DocumentDocumentType
 */
export enum DocumentDocumentType {
  Unspecified = 0,
  Identification = 1,
  AddressProof = 2,
  Contract = 3,
  LegalProcess = 4,
  Evidence = 5,
  Invoice = 6,
  Other = 7,
}
/**
 * Enumeration for DocumentStatus
 */
export enum DocumentStatus {
  Unspecified = 0,
  Pending = 1,
  Valid = 2,
  Rejected = 3,
  Expired = 4,
  Archived = 5,
}


/**
 * Interface for DocumentFileInfoModel
 */
export interface DocumentFileInfoModel {
  file_name: string;
  file_size: number;
  mime_type: string;
  file_url: string;
}
/**
 * Interface for DocumentMetadataModel
 */
export interface DocumentMetadataModel {
  issue_date?: string | null;
  expiry_date?: string | null;
  issuer?: string | null;
  notes?: string | null;
}

/**
 * Interface for DocumentModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface DocumentModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  client_id: string;
  demand_id?: string | null;
  document_type: DocumentDocumentType;
  status: DocumentStatus;
  file_info: DocumentFileInfoModel;
  metadata?: DocumentMetadataModel | null;
}

/**
 * ORM class for Document entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class DocumentORM {
  private static instance: DocumentORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b19490f507193aa7678742cfd6655';
    this.entityName = 'document';
    this.entityVersion = '102019bcc5c552f7d7fa90dc0b3dacd031d';
    this.taskId = '696b9c93e6e950bb2289f8b5';
    this.taskRootId = '693c2aa501d82a4f259f4ab4';
  }

  /**
   * Get singleton instance of DocumentORM
   */
  public static getInstance(): DocumentORM {
    if (!DocumentORM.instance) {
      DocumentORM.instance = new DocumentORM();
    }
    
    return DocumentORM.instance;
  }

  /**
   * Get document by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getDocumentByIDs(ids: string[]): Promise<DocumentModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete document by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteDocumentByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all Document records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllDocument(): Promise<DocumentModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Document record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertDocument(data: DocumentModel[]): Promise<DocumentModel[]> {
    const structured = data.map((item) => CreateData(DocumentModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Document records
   */
  async purgeAllDocument(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Document records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listDocument(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[DocumentModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get document by Id index
   * This function gets data by index.
   */
  async getDocumentById(
    id: string,
  ): Promise<DocumentModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) document by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDocumentById(
    id: string,
    data: DocumentModel
  ): Promise<DocumentModel[]> {
    const index = createIndexId(
      id
    );

    const values = DocumentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete document by Id index
   */
  async deleteDocumentById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get document by ClientId index
   * This function gets data by index.
   */
  async getDocumentByClientId(
    client_id: string,
  ): Promise<DocumentModel[]> {
    const index = createIndexClientId(
      client_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) document by ClientId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDocumentByClientId(
    client_id: string,
    data: DocumentModel
  ): Promise<DocumentModel[]> {
    const index = createIndexClientId(
      client_id
    );

    const values = DocumentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete document by ClientId index
   */
  async deleteDocumentByClientId(
    client_id: string
  ): Promise<void> {
    const index = createIndexClientId(
      client_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get document by DemandId index
   * This function gets data by index.
   */
  async getDocumentByDemandId(
    demand_id: string,
  ): Promise<DocumentModel[]> {
    const index = createIndexDemandId(
      demand_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) document by DemandId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDocumentByDemandId(
    demand_id: string,
    data: DocumentModel
  ): Promise<DocumentModel[]> {
    const index = createIndexDemandId(
      demand_id
    );

    const values = DocumentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete document by DemandId index
   */
  async deleteDocumentByDemandId(
    demand_id: string
  ): Promise<void> {
    const index = createIndexDemandId(
      demand_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get document by DocumentType index
   * This function gets data by index.
   */
  async getDocumentByDocumentType(
    document_type: DocumentDocumentType,
  ): Promise<DocumentModel[]> {
    const index = createIndexDocumentType(
      document_type
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) document by DocumentType index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDocumentByDocumentType(
    document_type: DocumentDocumentType,
    data: DocumentModel
  ): Promise<DocumentModel[]> {
    const index = createIndexDocumentType(
      document_type
    );

    const values = DocumentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete document by DocumentType index
   */
  async deleteDocumentByDocumentType(
    document_type: DocumentDocumentType
  ): Promise<void> {
    const index = createIndexDocumentType(
      document_type
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get document by Status index
   * This function gets data by index.
   */
  async getDocumentByStatus(
    status: DocumentStatus,
  ): Promise<DocumentModel[]> {
    const index = createIndexStatus(
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) document by Status index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDocumentByStatus(
    status: DocumentStatus,
    data: DocumentModel
  ): Promise<DocumentModel[]> {
    const index = createIndexStatus(
      status
    );

    const values = DocumentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete document by Status index
   */
  async deleteDocumentByStatus(
    status: DocumentStatus
  ): Promise<void> {
    const index = createIndexStatus(
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get document by DataCreator index
   * This function gets data by index.
   */
  async getDocumentByDataCreator(
    data_creator: string,
  ): Promise<DocumentModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) document by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDocumentByDataCreator(
    data_creator: string,
    data: DocumentModel
  ): Promise<DocumentModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = DocumentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete document by DataCreator index
   */
  async deleteDocumentByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get document by DataUpdater index
   * This function gets data by index.
   */
  async getDocumentByDataUpdater(
    data_updater: string,
  ): Promise<DocumentModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) document by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDocumentByDataUpdater(
    data_updater: string,
    data: DocumentModel
  ): Promise<DocumentModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = DocumentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete document by DataUpdater index
   */
  async deleteDocumentByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to DocumentModel data array
   */
  private resultToData(values: Data[]): DocumentModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return DocumentModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as DocumentModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized DocumentModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is DocumentModel => item !== null);
  }
}

/**
 * Convert DocumentModel data to Value array
 */
function DocumentModelToValues(data: DocumentModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'client_id', type: DataType.string, defaultValue: '' },
    { key: 'demand_id', type: DataType.string, defaultValue: null },
    { key: 'document_type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
    { key: 'file_info', type: DataType.object, defaultValue: {} },
    { key: 'metadata', type: DataType.object, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof DocumentModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to DocumentModel data
 */
function DocumentModelFromValues(values: Value[]): DocumentModel {
  const data: Partial<DocumentModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'client_id':
        data.client_id = ParseValue(value, DataType.string) as string;
        break;
      case 'demand_id':
        data.demand_id = ParseValue(value, DataType.string) as string | null;
        break;
      case 'document_type':
        data.document_type = ParseValue(value, DataType.enumeration) as DocumentDocumentType;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as DocumentStatus;
        break;
      case 'file_info':
        data.file_info = ParseValue(value, DataType.object) as DocumentFileInfoModel;
        break;
      case 'metadata':
        data.metadata = ParseValue(value, DataType.object) as DocumentMetadataModel | null;
        break;
    }
  }
  
  return data as DocumentModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for ClientId fields
 */
function createIndexClientId(
  client_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, client_id, 'client_id'),
  ];

  return {
    fields: ['client_id'],
    values
  };
}
/**
 * Create index for DemandId fields
 */
function createIndexDemandId(
  demand_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, demand_id, 'demand_id'),
  ];

  return {
    fields: ['demand_id'],
    values
  };
}
/**
 * Create index for DocumentType fields
 */
function createIndexDocumentType(
  document_type: DocumentDocumentType
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, document_type, 'document_type'),
  ];

  return {
    fields: ['document_type'],
    values
  };
}
/**
 * Create index for Status fields
 */
function createIndexStatus(
  status: DocumentStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['status'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default DocumentORM;